# Workflow to deploy code on server with actions

name: Build Parcel Packages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
  # pull_request:
  # branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: ğŸ› ï¸ Build & Deploy
    runs-on: ubuntu-latest
    # defaults:
    # run:
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: Path_Man Yarn Install and Parcel Build
        run: |
          cd path_man && yarn install
          yarn build
